name: Firebase Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Set Firebase Project
        run: firebase use ci-cd-demo-6a9d4 --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
